name: Archive Emotes

on:
  push:
  schedule:
  - cron: '*/10 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: latest
    - name: Archive
      run: npm run archive
    - name: Commit data
      run: |
        git config user.name "Archive"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        git commit -m "Archive from $(date -u)" || exit 0
        git push
